### PR TITLE
General docs

### PR DESCRIPTION
**Pull request by ndw**
This pull request:
1. Allows non-XML documents to flow between steps
2. Creates document properties and accessors for them
3. Removes the now unnecessary p:data element

### CODE REVIEW

**Comment by vojtechtoman** [comment]
What is the media-type story for output ports? I think that at least for the standard library (and the built-in compound steps such as `p:viewport`), we should say what media-types they produce. For some steps (such as `p:identity`) this is trivial, but what to expect if, say, you use `p:insert` to modify an SVG document in such a way that it is no longer an SVG document?

At the very least, I think there will have to be a step that can set (or 'cast') the media type of its input to the user-spupplied media type. I think this will be needed in cases when we know what the data is like but for some reason it has an incorrect or too unspecific media type.

An interesting case is the `p:xslt` step, which, I think, should honor the media type of whatever data floats from the underlying transformation, both the primary result and the secondary result documents.

Regarding dropping `p:data`, I feel a bit torn. On one hand it's good to see it go, but my feeling is that we will still need some kind of support for base64-encoding/decoding (if only to call legacy steps that expect the base64 encoded XML wrapper). But perhaps special steps for this is the way to go.

**Comment by ndw** [comment]
I agree we need a step to cast media types. Maybe we should just let the set-properties step do it. Alternatively, we could have a cast-as-media-type step. I also agree that we need base64 encode/decode steps. I'll add those.

I'm really not sure about media types on output ports. Yes, there's some symmetry, and yes, it's possible, but the value seems awfully limited. It would allow a small amount of static error checking, but most steps just mirror their input and many steps (p:xslt, p:xsl-formatter, p:xquery, p:load, p:http-request, probably others) would have to be marked as producing _/_ so you couldn't do anything useful with them statically anyway.

**Comment by vojtechtoman** [comment]
Regarding media types on output ports, I would like to keep it as simple as possible. But I think at least some kind of a minimal story is needed, at the very least to make sure that pipelines like the one below can function at all:

``` xml
...
<p:identity/>
<p:xinclude/>
...
```

The `p:xinclude` expects an XML media type, so the `p:identity` should at least preserve the media type information of its input data. If `p:identity` strips down the media type information, then the above snippet will not work if you pass an XML document to it.

But I guess this is all related to a broader question: what happens to the properties map as documents flow through the pipeline.

**Comment by ndw** [comment]
Right. I updated the top of section 7 to say that, like the base URI, the document properties go through unchanged. I don't actually think the note is wholly complete, but it's a stake in the ground.

**Comment by alexmilowski** [comment]
Maybe this should be called c:cast-as-content-type ?  The value space of "content-type" is a media type and documents have content types.

**Comment by vojtechtoman** [comment]
It just occurred to me that there may be more subtlety to 'properties go through unchanged' than is apparent at the first sight. Consider, for example, `p:store` - the output produced by this step does not relate to the input in the same way as, let's say, in the case of `p:identity` or `p:xinclude`; it describes the result of the step. If you use `p:store` to store a JPEG image, you still get an XML result document back - but do we want the media type of that XML document to be image/jpeg?

Kind of similar are the steps of the `p:xsl-formatter` variety where you could also argue what the output document properties should be. I know I am deviating from the main topic of the discussion here, but perhaps the solution lies in getting rid of the non-primary output ports and replacing them with primary output ports that produce the raw step result (that is PDF in the case of `p:xsl-formatter` etc.).

**Comment by ndw** [comment]
Yes, lots of steps will have to specify that they do change the media type. I was just putting a stake in the ground.

**Pull request merged**
